### ISSUE TITLE
nice work man

### ISSUE THREAD

**Issue by xak1989** [cochise/TimeManager#1]
There are a few suggestions for you if you do not mind.
1) Inject your watch function into MiniClockFu plugin (there is nothing happens when you click on MiniClockFu, it is possible to use for your function), it would be just great (I unfortunately do not know how).
2) Inside of your UI to make even 1 raid button calendar, it would be very convenient that something like this: http://www.warcraft-mods.com/Merdon-Raid-Calendar.html
3) It would be nice to be able to move your clock UI :)
4) It would be nice sound reproduction when displayed Alarm Message
5) It would be nice to step 1 min instead of 15 in Alarm Message

**Comment by cochise** [comment]
>4) It would be nice sound reproduction when displayed Alarm Message

You receive a chat notification, raid warning, and alarm sound when the alarm fires. Check your sound settings if you can't hear the alarm sound. Trigger the alarm for testing by typing `/run TimeManager_FireAlarm()` in your chat window.
